services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: argos
      MARIADB_USER: argos_user
      MARIADB_PASSWORD: ${ARGOS_DB_PASSWORD}

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - data

    # IMPORTANT: ne pas exposer 3306
    ports:
      - "127.0.0.1:3306:3306"

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data:

networks:
  # réseau DB (interne docker)
  data:
    name: argos-data
  proxy:
    external: true

