services:
  mariadb-private:
    image: mariadb:11.4
    container_name: mariadb-private
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_PRIVATE_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_PRIVATE_DATABASE}"
      MARIADB_USER: "${MARIADB_PRIVATE_USER}"
      MARIADB_PASSWORD: "${MARIADB_PRIVATE_PASSWORD}"
    volumes:
      - mariadb-private-data:/var/lib/mysql
    networks:
      - mariadb-private

  mariadb-public:
    image: mariadb:11.4
    container_name: mariadb-public
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_PUBLIC_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_PUBLIC_DATABASE}"
      MARIADB_USER: "${MARIADB_PUBLIC_USER}"
      MARIADB_PASSWORD: "${MARIADB_PUBLIC_PASSWORD}"
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mariadb-public

networks:
  mariadb-public:
    name: mariadb-public
  mariadb-private:
    name: mariadb-private

volumes:
  mariadb-private-data:
    name: mariadb-private-data
  mariadb-data:
    name: mariadb-data
