services:
  invoice-builder:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: invoice-builder
    restart: unless-stopped
    environment:
      SERVICE: all
      NODE_ENV: docker
      DB_DIRECTORY: /data
      PORT: 3000
      DEV_SERVER_URL: 0.0.0.0
    volumes:
      - ./data:/data
    ports:
      - "8086:3001"
    networks:
      - invoice-builder

networks:
  invoice-builder:
    name: invoice-builder